server:
  port: 9000
eureka:
  client:
    service-url:
      #当前Eureka Server对外暴露的服务地址
      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: depart-zuul
zuul:
  routes:
    depart-consumer-zuul-8080: /abc8080/**
    depart-consumer-zuul-8090: /abc8090/**
  ignored-services: "*"

  ratelimit:
    enabled: true #开启限流
    #设置限流策略
    #在一个3s大小的时间窗内，通过该zuul的用户数量、ip数量以及url数量都不能超过3个
    default-policy:
      refresh-interval: 3 #限流单位的时间窗大小 单位是秒
      quota: 1 #指定限流时间窗数量
      limit: 3 #指定的单位时间窗内启动限流的限定值
      type: user,origin,url #指定限流检验的类型

