server:
  port: 8300
eureka:
  client:
    register-with-eureka: false #指定当前主机是否需要想Eureka Server注册
    fetch-registry: false #指定当前主机是否从Eureka Server下载服务注册表
    service-url:
      #当前Eureka Server对外暴露的服务地址
      defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
