spring:
  application:
    name: consumer8080-1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  #设置zipkin server
  zipkin:
    base-url: http://http://localhost:9411/
  #设置采样比例为1.0 也就是全部采样
  sleuth:
    sampler:
      probability: 1.0

