
spring:
  application:
    name: depart-consumer-zuul
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    metadata-map:
      host-mark: running-host

feign:
  client:
    config:
      default:
        connectTimeout: 5000 #指定feign客户端连接提供者的超时时限
        readTimeout: 5000 #指定feign客户端连接上提供者后，向提供者提交请求，从提交时刻开始到接收响应，这个时段的超时时限
#负载均衡策略
#depart-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server:
  port: 8280
